name: js-linter
on: [push]
jobs:
    run-js-linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - run: npm install -g jshint
            - name: Create JSHint config file
              run: |
                echo '{ "esversion: 6"}' > .jshintrc

            - name: Lint all JS files
              run: |
                find . -name '*.js' -type f \
                | grep -v "^./source/8-ball/" \
                | xargs -I {} jshint --config .jshintrc {}